name: Rent59E-spider

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: |
          playwright install chromium --with-deps

      - name: Install Noto Sans TC font manually
        run: |
          sudo apt-get update
          sudo apt-get install -y fontconfig wget
          wget https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTF/TraditionalChinese/NotoSansCJKtc-Regular.otf
          sudo mv NotoSansCJKtc-Regular.otf /usr/share/fonts/
          sudo fc-cache -fv
          fc-list | grep "Noto Sans CJK TC"

      - name: Check installed fonts
        run: |
          find /usr/share/fonts -iname "*noto*"

      - name: Setup Google credential
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > service_account.json

      - name: Run spider script
        run: python 59E_spider.py

      - name: Run spider_taipei script
        run: python 59E_spider-taipei.py

      - name: Run spider_new_taipei script
        run: python 59E_spider-new_taipei.py

      - name: Run spider_new_taipei script
        run: python 59E_spider-kind3.py

      # 記得設定 Setting > Actions > General > Workflow permissions > Read and write permissions
      # 否則會報錯 403 權限問題
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "租屋資料更新：$(TZ=Asia/Taipei date '+%Y-%m-%d-%H-%M (%a)')" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
